#!/usr/bin/env python3
"""
Download PETSS station CSV tarballs from NOMADS, extract one station CSV,
load it into pandas, and plot total water level (TWL).

This version integrates with a generated PETSS station-map config file,
for example one produced by build_petss_station_map.py:

    python build_petss_station_map.py --latest --regions nwak --output-py petss_station_map.py

Then run the TWL plotter with station-name matching:

    python petss_csv_twl_plotter_integrated.py --location "Nome" --region nwak --outdir petss_data

Or refresh the station map from the latest PETSS storm tide text file before plotting:

    python petss_csv_twl_plotter_integrated.py --location "Nome" --region nwak --refresh-station-map

Direct station ID still works and bypasses station-name lookup:

    python petss_csv_twl_plotter_integrated.py --date 20260622 --cycle 06 --station-id 9468756 --outdir petss_data

Notes:
- NOMADS CSV tarball pattern:
  https://nomads.ncep.noaa.gov/pub/data/nccf/com/petss/prod/petss.YYYYMMDD/petss.tHHz.csv.tar.gz
- Extracted archive path commonly looks like:
  petss.tHHz.csv/petss.YYYYMMDD/tHHz.csv/<station_id>.csv
- PETSS CSV missing values are usually 9999.000.
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import json
import re
import subprocess
import sys
import tarfile
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import matplotlib.pyplot as plt
import pandas as pd

BASE_URL = "https://nomads.ncep.noaa.gov/pub/data/nccf/com/petss/prod"
RUN_CYCLES = ("00", "06", "12", "18")
MISSING_VALUES = [9999, 9999.0, 9999.000, -9999, -9999.0]

# Very small emergency fallback only. The preferred workflow is to use
# petss_station_map.py generated by build_petss_station_map.py.
FALLBACK_STATION_MAP = {
    "nome": "9468756",
    "nome norton sound": "9468756",
    "prudhoe bay": "9497645",
    "red dog": "9491094",
    "red dog dock": "9491094",
    "shishmaref": "9469854",
    "unalakleet": "9468333",
    "st michael": "9468132",
    "kaktovik": "9499176",
    "point hope": "9491873",
    "cape krusenstern": "9490571",
    "cape espenberg": "9490096",
    "wales": "9469515",
    "tin city": "9469439",
    "lost river": "9469338",
    "savoonga": "9468258",
    "nunam iqua": "9467551",
    "hooper bay": "9466931",
    "mekoryuk": "9466217",
    "quinhagak": "9465831",
    "platinum": "9465396",
    "unalska": "9462620",
    "unalaska": "9462620",
    "nikolski": "9462450",
    "cold bay": "ber0022",
    "akutan": "ber0020",
}


@dataclass(frozen=True)
class PetssCycle:
    date: str  # YYYYMMDD
    cycle: str  # HH, e.g. 06

    @property
    def tar_name(self) -> str:
        return f"petss.t{self.cycle}z.csv.tar.gz"

    @property
    def directory_url(self) -> str:
        return f"{BASE_URL}/petss.{self.date}"

    @property
    def tar_url(self) -> str:
        return f"{self.directory_url}/{self.tar_name}"

    @property
    def run_time_utc(self) -> pd.Timestamp:
        return pd.to_datetime(f"{self.date}{self.cycle}", format="%Y%m%d%H", utc=True)


@dataclass
class StationMaps:
    default_map: dict[str, str]
    ambiguous_map: dict[str, list[str]]
    metadata: dict[str, dict]
    source: str = "fallback"


def normalize_name(value: str) -> str:
    """
    Normalize user location queries the same way as the station-map builder.

    This should stay intentionally similar to normalize_station_key() in
    build_petss_station_map.py.
    """
    text = unicodedata.normalize("NFKD", str(value)).encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()

    # Remove trailing state tokens common in PETSS station labels.
    text = re.sub(r"[, \-]+ak$", "", text, flags=re.IGNORECASE)
    text = re.sub(r"[, \-]+alaska$", "", text, flags=re.IGNORECASE)

    text = text.replace("&", " and ")
    text = re.sub(r"[#'`’]", "", text)
    text = re.sub(r"[/_.:,;()\[\]{}\-]+", " ", text)

    replacements = {
        r"\bst\b": "st",
        r"\bpt\b": "point",
        r"\bent\b": "entrance",
        r"\brv\b": "river",
        r"\br\b": "river",
        r"\bsd\b": "sound",
        r"\bi\b": "island",
        r"\bis\b": "island",
        r"\bn\b": "north",
        r"\bs\b": "south",
        r"\be\b": "east",
        r"\bw\b": "west",
    }
    for pattern, repl in replacements.items():
        text = re.sub(pattern, repl, text)

    return re.sub(r"\s+", " ", text).strip()


def url_exists(url: str, timeout: int = 20) -> bool:
    """Return True if a URL is reachable. Some NOMADS paths may not support HEAD, so fall back to GET."""
    for method in ("HEAD", "GET"):
        try:
            req = Request(url, method=method, headers={"User-Agent": "petss-python-downloader/1.0"})
            with urlopen(req, timeout=timeout) as resp:
                return 200 <= resp.status < 400
        except HTTPError as exc:
            if exc.code == 405 and method == "HEAD":
                continue
            return False
        except URLError:
            return False
    return False


def find_latest_cycle(max_days_back: int = 3) -> PetssCycle:
    """Find the latest available PETSS CSV tarball on NOMADS."""
    now = datetime.now(timezone.utc)
    candidate_dates = [(now - timedelta(days=i)).strftime("%Y%m%d") for i in range(max_days_back + 1)]

    candidates: list[PetssCycle] = []
    for date in candidate_dates:
        for cycle in RUN_CYCLES:
            candidates.append(PetssCycle(date=date, cycle=cycle))

    candidates.sort(key=lambda c: c.run_time_utc, reverse=True)

    for candidate in candidates:
        if url_exists(candidate.tar_url):
            return candidate

    raise RuntimeError(f"Could not find a PETSS CSV tarball within the last {max_days_back} days.")


def download_file(url: str, output_path: Path, overwrite: bool = False) -> Path:
    """Download URL to output_path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.stat().st_size > 0 and not overwrite:
        print(f"Using cached file: {output_path}")
        return output_path

    print(f"Downloading: {url}")
    req = Request(url, headers={"User-Agent": "petss-python-downloader/1.0"})
    try:
        with urlopen(req, timeout=120) as resp, open(output_path, "wb") as f:
            f.write(resp.read())
    except HTTPError as exc:
        raise RuntimeError(f"HTTP {exc.code} while downloading {url}") from exc
    except URLError as exc:
        raise RuntimeError(f"Could not reach {url}: {exc}") from exc

    return output_path


def load_station_maps_from_py(path: Path) -> StationMaps:
    """
    Load DEFAULT_STATION_MAP, AMBIGUOUS_STATION_MAP, and STATION_METADATA
    from a generated Python config file.
    """
    if not path.exists():
        raise FileNotFoundError(path)

    spec = importlib.util.spec_from_file_location("petss_station_map_dynamic", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not import station map file: {path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    default_map = getattr(module, "DEFAULT_STATION_MAP", {})
    ambiguous_map = getattr(module, "AMBIGUOUS_STATION_MAP", {})
    metadata = getattr(module, "STATION_METADATA", {})

    if not isinstance(default_map, dict):
        raise ValueError(f"{path} has DEFAULT_STATION_MAP, but it is not a dict.")
    if not isinstance(ambiguous_map, dict):
        ambiguous_map = {}
    if not isinstance(metadata, dict):
        metadata = {}

    normalized_default = {normalize_name(k): str(v) for k, v in default_map.items()}
    normalized_ambiguous = {
        normalize_name(k): [str(item) for item in v]
        for k, v in ambiguous_map.items()
    }

    return StationMaps(
        default_map=normalized_default,
        ambiguous_map=normalized_ambiguous,
        metadata=metadata,
        source=str(path),
    )


def load_station_maps_from_json(path: Path) -> StationMaps:
    """Load station maps from JSON produced by build_petss_station_map.py --write-json."""
    payload = json.loads(path.read_text(encoding="utf-8"))

    default_map = payload.get("default_station_map", payload.get("DEFAULT_STATION_MAP", {}))
    ambiguous_map = payload.get("ambiguous_station_map", payload.get("AMBIGUOUS_STATION_MAP", {}))
    metadata = payload.get("station_metadata", payload.get("STATION_METADATA", {}))

    return StationMaps(
        default_map={normalize_name(k): str(v) for k, v in default_map.items()},
        ambiguous_map={normalize_name(k): [str(item) for item in v] for k, v in ambiguous_map.items()},
        metadata=metadata,
        source=str(path),
    )


def load_station_maps_from_csv(path: Path) -> StationMaps:
    """
    Load a simple station CSV with station_id and station_name columns.

    This is still supported, but a generated Python or JSON station map is
    preferred because it includes aliases and ambiguous names.
    """
    df = pd.read_csv(path, dtype=str)
    df.columns = [c.strip().lower() for c in df.columns]

    required = {"station_id", "station_name"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Station map CSV is missing required columns: {sorted(missing)}")

    alias_to_ids: dict[str, set[str]] = {}
    metadata: dict[str, dict] = {}

    for row in df.itertuples(index=False):
        station_id = str(getattr(row, "station_id")).strip()
        station_name = str(getattr(row, "station_name")).strip()
        alias = normalize_name(station_name)
        alias_to_ids.setdefault(alias, set()).add(station_id)
        metadata.setdefault(station_id, {"station_id": station_id, "station_name": station_name, "aliases": [alias]})

    default_map = {alias: sorted(ids)[0] for alias, ids in alias_to_ids.items() if len(ids) == 1}
    ambiguous_map = {alias: sorted(ids) for alias, ids in alias_to_ids.items() if len(ids) > 1}

    return StationMaps(default_map=default_map, ambiguous_map=ambiguous_map, metadata=metadata, source=str(path))


def load_station_maps(path: Path | None) -> StationMaps:
    """
    Load generated station maps.

    Priority:
      1. Explicit --station-map path
      2. ./petss_station_map.py if present
      3. fallback mini map
    """
    if path is None:
        candidate = Path("petss_station_map.py")
        if candidate.exists():
            path = candidate

    if path is None:
        return StationMaps(
            default_map={normalize_name(k): str(v) for k, v in FALLBACK_STATION_MAP.items()},
            ambiguous_map={},
            metadata={},
            source="built-in fallback",
        )

    suffix = path.suffix.lower()
    if suffix == ".py":
        return load_station_maps_from_py(path)
    if suffix == ".json":
        return load_station_maps_from_json(path)
    if suffix == ".csv":
        return load_station_maps_from_csv(path)

    raise ValueError(
        f"Unsupported station map format: {path}. "
        "Use a .py file from build_petss_station_map.py, a .json file, or a simple .csv."
    )


def refresh_station_map(
    *,
    builder_script: Path,
    output_py: Path,
    region: str,
    date: str | None,
    cycle: str | None,
    latest: bool,
    overwrite: bool,
) -> None:
    """
    Run build_petss_station_map.py before resolving a station name.

    This keeps the station-map extraction logic out of the TWL plotter.
    """
    if not builder_script.exists():
        raise FileNotFoundError(
            f"Station-map builder not found: {builder_script}. "
            "Place build_petss_station_map.py next to this script or pass --station-map-builder."
        )

    cmd = [
        sys.executable,
        str(builder_script),
        "--regions",
        region,
        "--output-py",
        str(output_py),
    ]

    if latest or not (date and cycle):
        cmd.append("--latest")
    else:
        cmd.extend(["--date", date, "--cycle", cycle])

    if overwrite:
        # The builder itself uses cached raw text files if present. There is no
        # explicit overwrite flag in the current builder, so this argument is not
        # forwarded. It is kept here for future compatibility.
        pass

    print("Refreshing station map:")
    print("  " + " ".join(cmd))
    subprocess.run(cmd, check=True)


def station_label_from_metadata(station_id: str, maps: StationMaps) -> str | None:
    """Return a human-readable station label from STATION_METADATA when available."""
    item = maps.metadata.get(str(station_id))
    if isinstance(item, dict):
        name = item.get("station_name")
        if isinstance(name, str) and name.strip():
            return name.strip()
    return None


def resolve_station_id(
    *,
    station_id: str | None,
    location: str | None,
    station_maps: StationMaps,
) -> tuple[str, str | None]:
    """Resolve station_id from explicit station ID or station-name query."""
    if station_id:
        sid = str(station_id).strip()
        return sid, station_label_from_metadata(sid, station_maps)

    if not location:
        raise ValueError("Provide either --station-id or --location.")

    query_norm = normalize_name(location)

    # Exact alias lookup.
    if query_norm in station_maps.ambiguous_map:
        ids = station_maps.ambiguous_map[query_norm]
        raise ValueError(
            f"Location '{location}' is ambiguous in {station_maps.source}: "
            f"{', '.join(ids)}. Use --station-id."
        )

    if query_norm in station_maps.default_map:
        sid = station_maps.default_map[query_norm]
        return sid, station_label_from_metadata(sid, station_maps) or location

    # Single contains match.
    contains = [
        (alias, sid)
        for alias, sid in station_maps.default_map.items()
        if query_norm in alias
    ]
    unique_ids = sorted({sid for _alias, sid in contains})
    if len(unique_ids) == 1:
        sid = unique_ids[0]
        return sid, station_label_from_metadata(sid, station_maps) or location
    if len(unique_ids) > 1:
        choices = ", ".join(f"{alias} ({sid})" for alias, sid in contains[:15])
        raise ValueError(
            f"Location '{location}' matched multiple stations in {station_maps.source}: "
            f"{choices}. Use --station-id."
        )

    # Fuzzy matching over aliases.
    close = difflib.get_close_matches(query_norm, list(station_maps.default_map.keys()), n=8, cutoff=0.65)
    close_ids = sorted({station_maps.default_map[name] for name in close})
    if len(close_ids) == 1 and close:
        sid = close_ids[0]
        print(f"Matched location '{location}' to alias '{close[0]}' ({sid}) from {station_maps.source}.")
        return sid, station_label_from_metadata(sid, station_maps) or close[0]

    if close:
        choices = ", ".join(f"{name} ({station_maps.default_map[name]})" for name in close)
        raise ValueError(
            f"Could not uniquely match '{location}'. Close matches from {station_maps.source}: "
            f"{choices}. Use --station-id."
        )

    raise ValueError(
        f"Could not match location '{location}' to a station ID using {station_maps.source}. "
        "Try --station-id, run with --refresh-station-map, or pass --station-map petss_station_map.py."
    )


def safe_tar_member_name(member: tarfile.TarInfo) -> str:
    """Return normalized member name and reject unsafe absolute/path-traversal names."""
    name = member.name.replace("\\", "/")
    parts = [p for p in name.split("/") if p not in ("", ".")]
    if any(p == ".." for p in parts) or name.startswith("/"):
        raise ValueError(f"Unsafe path in tar archive: {member.name}")
    return "/".join(parts)


def find_station_member(tar_path: Path, station_id: str) -> tarfile.TarInfo:
    """Find a station CSV member inside the PETSS tarball."""
    target = f"{station_id}.csv".lower()

    with tarfile.open(tar_path, "r:gz") as tf:
        matches = []
        for member in tf.getmembers():
            if not member.isfile():
                continue
            name = safe_tar_member_name(member)
            if Path(name).name.lower() == target:
                matches.append(member)

        if len(matches) == 1:
            return matches[0]
        if len(matches) > 1:
            names = [m.name for m in matches]
            raise RuntimeError(f"Found multiple CSVs for station {station_id}: {names}")

    raise FileNotFoundError(f"Station CSV {station_id}.csv was not found in {tar_path}")


def extract_station_csv(tar_path: Path, station_id: str, output_dir: Path, overwrite: bool = False) -> Path:
    """Extract only the requested station CSV from the tarball."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{station_id}.csv"

    if output_path.exists() and output_path.stat().st_size > 0 and not overwrite:
        print(f"Using cached station CSV: {output_path}")
        return output_path

    with tarfile.open(tar_path, "r:gz") as tf:
        member = find_station_member(tar_path, station_id)
        extracted = tf.extractfile(member)
        if extracted is None:
            raise RuntimeError(f"Could not extract {member.name}")
        output_path.write_bytes(extracted.read())

    print(f"Extracted station CSV: {output_path}")
    return output_path


def read_petss_station_csv(
    csv_path: Path,
    cycle: PetssCycle | None = None,
    station_id: str | None = None,
    station_name: str | None = None,
) -> pd.DataFrame:
    """Read a PETSS station CSV and return a cleaned pandas DataFrame."""
    df = pd.read_csv(csv_path, skipinitialspace=True)
    df.columns = [c.strip() for c in df.columns]

    if "TIME" not in df.columns:
        raise ValueError(f"Expected a TIME column in {csv_path}; columns are: {list(df.columns)}")

    df["valid_time"] = pd.to_datetime(df["TIME"].astype(str), format="%Y%m%d%H%M", utc=True, errors="coerce")

    numeric_cols = [c for c in df.columns if c not in {"TIME", "valid_time"}]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].where(~df[col].isin(MISSING_VALUES), pd.NA)

    if cycle is not None:
        df["run_time"] = cycle.run_time_utc
        df["forecast_hour"] = (df["valid_time"] - cycle.run_time_utc) / pd.Timedelta(hours=1)
    else:
        df["run_time"] = pd.NaT
        df["forecast_hour"] = pd.NA

    if station_id is None:
        station_id = csv_path.stem

    df["station_id"] = str(station_id)
    df["station_name"] = station_name

    first_cols = ["station_id", "station_name", "run_time", "valid_time", "forecast_hour"]
    other_cols = [c for c in df.columns if c not in first_cols]
    return df[first_cols + other_cols]


def download_and_read_station(
    *,
    date: str | None,
    cycle_hour: str | None,
    station_id: str | None,
    location: str | None,
    region: str,
    outdir: Path,
    station_map_path: Path | None,
    refresh_map: bool,
    station_map_builder: Path,
    overwrite: bool,
) -> tuple[pd.DataFrame, PetssCycle, Path]:
    """Complete workflow: resolve cycle, resolve station, download tarball, extract CSV, read DataFrame."""
    if date and cycle_hour:
        cycle = PetssCycle(date=date, cycle=f"{int(cycle_hour):02d}")
    elif date or cycle_hour:
        raise ValueError("Use both --date and --cycle together, or omit both to use latest available.")
    else:
        cycle = find_latest_cycle()
        print(f"Latest available PETSS CSV cycle appears to be {cycle.date} t{cycle.cycle}z")

    # If requested, rebuild petss_station_map.py using the same date/cycle when provided,
    # otherwise use latest available storm tide text file.
    if refresh_map:
        target_station_map = station_map_path or Path("petss_station_map.py")
        refresh_station_map(
            builder_script=station_map_builder,
            output_py=target_station_map,
            region=region,
            date=date,
            cycle=cycle_hour,
            latest=not (date and cycle_hour),
            overwrite=overwrite,
        )
        station_map_path = target_station_map

    station_maps = load_station_maps(station_map_path)
    print(f"Station-map source: {station_maps.source}")

    resolved_station_id, resolved_station_name = resolve_station_id(
        station_id=station_id,
        location=location,
        station_maps=station_maps,
    )
    print(f"Using station: {resolved_station_id}" + (f" ({resolved_station_name})" if resolved_station_name else ""))

    tar_path = outdir / "raw" / cycle.date / f"t{cycle.cycle}z" / cycle.tar_name
    download_file(cycle.tar_url, tar_path, overwrite=overwrite)

    station_csv_dir = outdir / "stations" / cycle.date / f"t{cycle.cycle}z"
    csv_path = extract_station_csv(tar_path, resolved_station_id, station_csv_dir, overwrite=overwrite)

    df = read_petss_station_csv(
        csv_path,
        cycle=cycle,
        station_id=resolved_station_id,
        station_name=resolved_station_name,
    )
    return df, cycle, csv_path


def plot_twl(
    df: pd.DataFrame,
    output_path: Path,
    station_label: str | None = None,
    title: str | None = None,
    scenario_low_label: str = "Lower-end scenario",
    scenario_high_label: str = "Higher-end scenario",
    main_label: str = "Most likely water level forecast",
    show_scenario_lines: bool = True,
) -> Path:
    """
    Customer-facing PETSS total water level forecast graphic.

    This plot intentionally keeps the graphic simple:
      - Starts at the current model run time.
      - Plots only forecast total water level information.
      - Omits tide and observed water level by default.
      - Uses plain-language scenario labels instead of percentile terminology.

    PETSS CSV detail:
      TWL, TWL10p, and TWL90p are usually populated only on forecast rows,
      while OB and TIDE are much denser. We therefore drop NaNs from the
      forecast columns before plotting.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if "TWL" not in df.columns:
        raise ValueError(f"No TWL column found. Available columns: {list(df.columns)}")

    plot_df = df.sort_values("valid_time").copy()
    plot_df["valid_time"] = pd.to_datetime(plot_df["valid_time"], utc=True, errors="coerce")

    # Keep only the forecast portion from model initialization onward.
    if "run_time" in plot_df.columns and plot_df["run_time"].notna().any():
        run_time = pd.to_datetime(plot_df["run_time"].dropna().iloc[0], utc=True)
        plot_df = plot_df[plot_df["valid_time"] >= run_time].copy()
    else:
        run_time = pd.NaT

    # TWL forecast values are sparse/hourly. Drop NaNs so matplotlib connects
    # the actual forecast points rather than breaking on intervening missing rows.
    twl_df = plot_df.dropna(subset=["valid_time", "TWL"]).copy()

    fig, ax = plt.subplots(figsize=(12, 6))

    # Scenario envelope. Keep row-wise min/max because some files may not have
    # TWL10p/TWL90p ordered the way the labels imply.
    pct_available = {"TWL10p", "TWL90p"}.issubset(plot_df.columns)
    if pct_available:
        pct_df = plot_df.dropna(subset=["valid_time", "TWL10p", "TWL90p"]).copy()
        if not pct_df.empty:
            p10 = pd.to_numeric(pct_df["TWL10p"], errors="coerce")
            p90 = pd.to_numeric(pct_df["TWL90p"], errors="coerce")
            lower = pd.concat([p10, p90], axis=1).min(axis=1)
            upper = pd.concat([p10, p90], axis=1).max(axis=1)

            ax.fill_between(
                pct_df["valid_time"],
                lower,
                upper,
                alpha=0.25,
                label=f"Likely range: {scenario_low_label} to {scenario_high_label}",
            )

            if show_scenario_lines:
                ax.plot(
                    pct_df["valid_time"],
                    lower,
                    linewidth=1.5,
                    linestyle="--",
                    label=scenario_low_label,
                )
                ax.plot(
                    pct_df["valid_time"],
                    upper,
                    linewidth=1.5,
                    linestyle="--",
                    label=scenario_high_label,
                )

    if not twl_df.empty:
        ax.plot(
            twl_df["valid_time"],
            pd.to_numeric(twl_df["TWL"], errors="coerce"),
            linewidth=3,
            marker="o",
            markersize=2.5,
            label=main_label,
        )
    else:
        print("Warning: TWL column exists but contains no valid forecast values to plot.")

    label = station_label or str(plot_df["station_id"].iloc[0])
    if title is None:
        if pd.notna(run_time):
            run_str = pd.Timestamp(run_time).strftime("%Y-%m-%d %HZ")
            title = f"Total Water Level Forecast for {label} Forecast issued: {run_str}"
        else:
            title = f"Total Water Level Forecast for {label}"

    ax.set_title(title, fontsize=15, fontweight="bold")
    ax.set_xlabel("Date and time (UTC)", fontsize=12)
    ax.set_ylabel("Water level (feet)", fontsize=12)
    ax.grid(True, alpha=0.35)
    ax.legend(loc="best", frameon=True)
    ax.tick_params(axis="both", labelsize=10)

    # Add a short plain-language note without using percentile jargon.
    note = (
        "Shaded area shows a reasonable range of outcomes."
        "Actual water levels may fall outside this range."
    )
    ax.text(
        0.01,
        0.02,
        note,
        transform=ax.transAxes,
        fontsize=9,
        va="bottom",
        ha="left",
        bbox={"boxstyle": "round,pad=0.35", "facecolor": "white", "alpha": 0.8, "edgecolor": "0.8"},
    )

    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)
    print(f"Wrote plot: {output_path}")
    return output_path


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download PETSS CSV tarball, extract a station CSV, and plot TWL.")

    parser.add_argument("--date", help="PETSS date in YYYYMMDD. Omit with --cycle to auto-detect latest available.")
    parser.add_argument("--cycle", choices=RUN_CYCLES, help="Cycle hour: 00, 06, 12, or 18. Omit with --date to auto-detect latest available.")

    station_group = parser.add_mutually_exclusive_group(required=True)
    station_group.add_argument("--station-id", help="Station ID, e.g. 9468756 for Nome.")
    station_group.add_argument("--location", help="Station name or partial name, e.g. Nome.")

    parser.add_argument("--region", default="nwak", help="PETSS text-region code used to build station-name map. Default: nwak.")
    parser.add_argument(
        "--station-map",
        type=Path,
        help=(
            "Optional generated station map. Preferred: petss_station_map.py from build_petss_station_map.py. "
            "Also supports .json or simple .csv."
        ),
    )
    parser.add_argument(
        "--refresh-station-map",
        action="store_true",
        help="Run build_petss_station_map.py before resolving --location.",
    )
    parser.add_argument(
        "--station-map-builder",
        type=Path,
        default=Path("build_petss_station_map.py"),
        help="Path to build_petss_station_map.py. Used only with --refresh-station-map.",
    )
    parser.add_argument("--outdir", type=Path, default=Path("petss_data"), help="Output/cache directory.")
    parser.add_argument("--overwrite", action="store_true", help="Re-download/re-extract existing files.")
    parser.add_argument("--no-plot", action="store_true", help="Only download/extract/read/write cleaned CSV; do not plot.")
    parser.add_argument("--scenario-low-label", default="Lower-end scenario", help="Plain-language label for the lower scenario line.")
    parser.add_argument("--scenario-high-label", default="Higher-end scenario", help="Plain-language label for the higher scenario line.")
    parser.add_argument("--main-label", default="Most likely water level forecast", help="Plain-language label for the TWL forecast line.")
    parser.add_argument("--hide-scenario-lines", action="store_true", help="Show only the shaded scenario range and main TWL line.")

    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)

    try:
        df, cycle, csv_path = download_and_read_station(
            date=args.date,
            cycle_hour=args.cycle,
            station_id=args.station_id,
            location=args.location,
            region=args.region,
            outdir=args.outdir,
            station_map_path=args.station_map,
            refresh_map=args.refresh_station_map,
            station_map_builder=args.station_map_builder,
            overwrite=args.overwrite,
        )

        station_id = str(df["station_id"].iloc[0])
        products_dir = args.outdir / "products" / cycle.date / f"t{cycle.cycle}z"
        products_dir.mkdir(parents=True, exist_ok=True)

        cleaned_path = products_dir / f"petss_{cycle.date}_t{cycle.cycle}z_{station_id}_clean.csv"
        df.to_csv(cleaned_path, index=False)
        print(f"Wrote cleaned CSV: {cleaned_path}")

        if not args.no_plot:
            station_name = df["station_name"].iloc[0]
            station_label = f"{station_name} ({station_id})" if isinstance(station_name, str) and station_name else station_id
            plot_path = products_dir / f"petss_{cycle.date}_t{cycle.cycle}z_{station_id}_twl.png"
            plot_twl(
                df,
                plot_path,
                station_label=station_label,
                scenario_low_label=args.scenario_low_label,
                scenario_high_label=args.scenario_high_label,
                main_label=args.main_label,
                show_scenario_lines=not args.hide_scenario_lines,
            )

        print("\nDataFrame preview:")
        with pd.option_context("display.max_columns", 20, "display.width", 160):
            print(df.head())

        print(f"\nOriginal station CSV: {csv_path}")
        return 0

    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
