#!/usr/bin/env python3
"""
Download PETSS station CSV tarballs from NOMADS, extract one station CSV,
load it into pandas, and plot total water level (TWL).

This version integrates with a generated PETSS station-map config file,
for example one produced by build_petss_station_map.py:

    python build_petss_station_map.py --latest --regions nwak --output-py petss_station_map.py

Then run the TWL plotter with station-name matching:

    python petss_csv_twl_plotter_integrated.py --location "Nome" --region nwak --outdir petss_data

Or refresh the station map from the latest PETSS storm tide text file before plotting:

    python petss_csv_twl_plotter_integrated.py --location "Nome" --region nwak --refresh-station-map

Direct station ID still works and bypasses station-name lookup:

    python petss_csv_twl_plotter_integrated.py --date 20260622 --cycle 06 --station-id 9468756 --outdir petss_data

Notes:
- NOMADS CSV tarball pattern:
  https://nomads.ncep.noaa.gov/pub/data/nccf/com/petss/prod/petss.YYYYMMDD/petss.tHHz.csv.tar.gz
- Extracted archive path commonly looks like:
  petss.tHHz.csv/petss.YYYYMMDD/tHHz.csv/<station_id>.csv
- PETSS CSV missing values are usually 9999.000.
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import json
import re
import subprocess
import sys
import tarfile
import textwrap
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from zoneinfo import ZoneInfo

import matplotlib.pyplot as plt
import pandas as pd

BASE_URL = "https://nomads.ncep.noaa.gov/pub/data/nccf/com/petss/prod"
RUN_CYCLES = ("00", "06", "12", "18")
MISSING_VALUES = [9999, 9999.0, 9999.000, -9999, -9999.0]

# Very small emergency fallback only. The preferred workflow is to use
# petss_station_map.py generated by build_petss_station_map.py.
FALLBACK_STATION_MAP = {
    "nome": "9468756",
    "nome norton sound": "9468756",
    "prudhoe bay": "9497645",
    "red dog": "9491094",
    "red dog dock": "9491094",
    "shishmaref": "9469854",
    "unalakleet": "9468333",
    "st michael": "9468132",
    "kaktovik": "9499176",
    "point hope": "9491873",
    "cape krusenstern": "9490571",
    "cape espenberg": "9490096",
    "wales": "9469515",
    "tin city": "9469439",
    "lost river": "9469338",
    "savoonga": "9468258",
    "nunam iqua": "9467551",
    "hooper bay": "9466931",
    "mekoryuk": "9466217",
    "quinhagak": "9465831",
    "platinum": "9465396",
    "unalska": "9462620",
    "unalaska": "9462620",
    "nikolski": "9462450",
    "cold bay": "ber0022",
    "akutan": "ber0020",
}


@dataclass(frozen=True)
class PetssCycle:
    date: str  # YYYYMMDD
    cycle: str  # HH, e.g. 06

    @property
    def tar_name(self) -> str:
        return f"petss.t{self.cycle}z.csv.tar.gz"

    @property
    def directory_url(self) -> str:
        return f"{BASE_URL}/petss.{self.date}"

    @property
    def tar_url(self) -> str:
        return f"{self.directory_url}/{self.tar_name}"

    @property
    def run_time_utc(self) -> pd.Timestamp:
        return pd.to_datetime(f"{self.date}{self.cycle}", format="%Y%m%d%H", utc=True)


@dataclass
class StationMaps:
    default_map: dict[str, str]
    ambiguous_map: dict[str, list[str]]
    metadata: dict[str, dict]
    source: str = "fallback"


@dataclass
class DatumConversion:
    station_id: str
    vertical_datum: str = "MLLW"
    mhhw_minus_mllw_ft: float | None = None
    coops_station_id: str | None = None
    coops_station_name: str | None = None
    datum_epoch: str | None = None
    source: str | None = None


def normalize_name(value: str) -> str:
    """
    Normalize user location queries the same way as the station-map builder.

    This should stay intentionally similar to normalize_station_key() in
    build_petss_station_map.py.
    """
    text = unicodedata.normalize("NFKD", str(value)).encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()

    # Remove trailing state tokens common in PETSS station labels.
    text = re.sub(r"[, \-]+ak$", "", text, flags=re.IGNORECASE)
    text = re.sub(r"[, \-]+alaska$", "", text, flags=re.IGNORECASE)

    text = text.replace("&", " and ")
    text = re.sub(r"[#'`’]", "", text)
    text = re.sub(r"[/_.:,;()\[\]{}\-]+", " ", text)

    replacements = {
        r"\bst\b": "st",
        r"\bpt\b": "point",
        r"\bent\b": "entrance",
        r"\brv\b": "river",
        r"\br\b": "river",
        r"\bsd\b": "sound",
        r"\bi\b": "island",
        r"\bis\b": "island",
        r"\bn\b": "north",
        r"\bs\b": "south",
        r"\be\b": "east",
        r"\bw\b": "west",
    }
    for pattern, repl in replacements.items():
        text = re.sub(pattern, repl, text)

    return re.sub(r"\s+", " ", text).strip()


def url_exists(url: str, timeout: int = 20) -> bool:
    """Return True if a URL is reachable. Some NOMADS paths may not support HEAD, so fall back to GET."""
    for method in ("HEAD", "GET"):
        try:
            req = Request(url, method=method, headers={"User-Agent": "petss-python-downloader/1.0"})
            with urlopen(req, timeout=timeout) as resp:
                return 200 <= resp.status < 400
        except HTTPError as exc:
            if exc.code == 405 and method == "HEAD":
                continue
            return False
        except URLError:
            return False
    return False


def find_latest_cycle(max_days_back: int = 3) -> PetssCycle:
    """Find the latest available PETSS CSV tarball on NOMADS."""
    now = datetime.now(timezone.utc)
    candidate_dates = [(now - timedelta(days=i)).strftime("%Y%m%d") for i in range(max_days_back + 1)]

    candidates: list[PetssCycle] = []
    for date in candidate_dates:
        for cycle in RUN_CYCLES:
            candidates.append(PetssCycle(date=date, cycle=cycle))

    candidates.sort(key=lambda c: c.run_time_utc, reverse=True)

    for candidate in candidates:
        if url_exists(candidate.tar_url):
            return candidate

    raise RuntimeError(f"Could not find a PETSS CSV tarball within the last {max_days_back} days.")


def download_file(url: str, output_path: Path, overwrite: bool = False) -> Path:
    """Download URL to output_path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.stat().st_size > 0 and not overwrite:
        print(f"Using cached file: {output_path}")
        return output_path

    print(f"Downloading: {url}")
    req = Request(url, headers={"User-Agent": "petss-python-downloader/1.0"})
    try:
        with urlopen(req, timeout=120) as resp, open(output_path, "wb") as f:
            f.write(resp.read())
    except HTTPError as exc:
        raise RuntimeError(f"HTTP {exc.code} while downloading {url}") from exc
    except URLError as exc:
        raise RuntimeError(f"Could not reach {url}: {exc}") from exc

    return output_path


def load_station_maps_from_py(path: Path) -> StationMaps:
    """
    Load DEFAULT_STATION_MAP, AMBIGUOUS_STATION_MAP, and STATION_METADATA
    from a generated Python config file.
    """
    if not path.exists():
        raise FileNotFoundError(path)

    spec = importlib.util.spec_from_file_location("petss_station_map_dynamic", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not import station map file: {path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    default_map = getattr(module, "DEFAULT_STATION_MAP", {})
    ambiguous_map = getattr(module, "AMBIGUOUS_STATION_MAP", {})
    metadata = getattr(module, "STATION_METADATA", {})

    if not isinstance(default_map, dict):
        raise ValueError(f"{path} has DEFAULT_STATION_MAP, but it is not a dict.")
    if not isinstance(ambiguous_map, dict):
        ambiguous_map = {}
    if not isinstance(metadata, dict):
        metadata = {}

    normalized_default = {normalize_name(k): str(v) for k, v in default_map.items()}
    normalized_ambiguous = {
        normalize_name(k): [str(item) for item in v]
        for k, v in ambiguous_map.items()
    }

    return StationMaps(
        default_map=normalized_default,
        ambiguous_map=normalized_ambiguous,
        metadata=metadata,
        source=str(path),
    )


def load_station_maps_from_json(path: Path) -> StationMaps:
    """Load station maps from JSON produced by build_petss_station_map.py --write-json."""
    payload = json.loads(path.read_text(encoding="utf-8"))

    default_map = payload.get("default_station_map", payload.get("DEFAULT_STATION_MAP", {}))
    ambiguous_map = payload.get("ambiguous_station_map", payload.get("AMBIGUOUS_STATION_MAP", {}))
    metadata = payload.get("station_metadata", payload.get("STATION_METADATA", {}))

    return StationMaps(
        default_map={normalize_name(k): str(v) for k, v in default_map.items()},
        ambiguous_map={normalize_name(k): [str(item) for item in v] for k, v in ambiguous_map.items()},
        metadata=metadata,
        source=str(path),
    )


def load_station_maps_from_csv(path: Path) -> StationMaps:
    """
    Load a simple station CSV with station_id and station_name columns.

    This is still supported, but a generated Python or JSON station map is
    preferred because it includes aliases and ambiguous names.
    """
    df = pd.read_csv(path, dtype=str)
    df.columns = [c.strip().lower() for c in df.columns]

    required = {"station_id", "station_name"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Station map CSV is missing required columns: {sorted(missing)}")

    alias_to_ids: dict[str, set[str]] = {}
    metadata: dict[str, dict] = {}

    for row in df.itertuples(index=False):
        station_id = str(getattr(row, "station_id")).strip()
        station_name = str(getattr(row, "station_name")).strip()
        alias = normalize_name(station_name)
        alias_to_ids.setdefault(alias, set()).add(station_id)
        metadata.setdefault(station_id, {"station_id": station_id, "station_name": station_name, "aliases": [alias]})

    default_map = {alias: sorted(ids)[0] for alias, ids in alias_to_ids.items() if len(ids) == 1}
    ambiguous_map = {alias: sorted(ids) for alias, ids in alias_to_ids.items() if len(ids) > 1}

    return StationMaps(default_map=default_map, ambiguous_map=ambiguous_map, metadata=metadata, source=str(path))


def load_station_maps(path: Path | None) -> StationMaps:
    """
    Load generated station maps.

    Priority:
      1. Explicit --station-map path
      2. ./petss_station_map.py if present
      3. fallback mini map
    """
    if path is None:
        candidate = Path("petss_station_map.py")
        if candidate.exists():
            path = candidate

    if path is None:
        return StationMaps(
            default_map={normalize_name(k): str(v) for k, v in FALLBACK_STATION_MAP.items()},
            ambiguous_map={},
            metadata={},
            source="built-in fallback",
        )

    suffix = path.suffix.lower()
    if suffix == ".py":
        return load_station_maps_from_py(path)
    if suffix == ".json":
        return load_station_maps_from_json(path)
    if suffix == ".csv":
        return load_station_maps_from_csv(path)

    raise ValueError(
        f"Unsupported station map format: {path}. "
        "Use a .py file from build_petss_station_map.py, a .json file, or a simple .csv."
    )


def refresh_station_map(
    *,
    builder_script: Path,
    output_py: Path,
    region: str,
    date: str | None,
    cycle: str | None,
    latest: bool,
    overwrite: bool,
) -> None:
    """
    Run build_petss_station_map.py before resolving a station name.

    This keeps the station-map extraction logic out of the TWL plotter.
    """
    if not builder_script.exists():
        raise FileNotFoundError(
            f"Station-map builder not found: {builder_script}. "
            "Place build_petss_station_map.py next to this script or pass --station-map-builder."
        )

    cmd = [
        sys.executable,
        str(builder_script),
        "--regions",
        region,
        "--output-py",
        str(output_py),
    ]

    if latest or not (date and cycle):
        cmd.append("--latest")
    else:
        cmd.extend(["--date", date, "--cycle", cycle])

    if overwrite:
        # The builder itself uses cached raw text files if present. There is no
        # explicit overwrite flag in the current builder, so this argument is not
        # forwarded. It is kept here for future compatibility.
        pass

    print("Refreshing station map:")
    print("  " + " ".join(cmd))
    subprocess.run(cmd, check=True)


def station_label_from_metadata(station_id: str, maps: StationMaps) -> str | None:
    """Return a human-readable station label from STATION_METADATA when available."""
    item = maps.metadata.get(str(station_id))
    if isinstance(item, dict):
        name = item.get("station_name")
        if isinstance(name, str) and name.strip():
            return name.strip()
    return None


def resolve_station_id(
    *,
    station_id: str | None,
    location: str | None,
    station_maps: StationMaps,
) -> tuple[str, str | None]:
    """Resolve station_id from explicit station ID or station-name query."""
    if station_id:
        sid = str(station_id).strip()
        return sid, station_label_from_metadata(sid, station_maps)

    if not location:
        raise ValueError("Provide either --station-id or --location.")

    query_norm = normalize_name(location)

    # Exact alias lookup.
    if query_norm in station_maps.ambiguous_map:
        ids = station_maps.ambiguous_map[query_norm]
        raise ValueError(
            f"Location '{location}' is ambiguous in {station_maps.source}: "
            f"{', '.join(ids)}. Use --station-id."
        )

    if query_norm in station_maps.default_map:
        sid = station_maps.default_map[query_norm]
        return sid, station_label_from_metadata(sid, station_maps) or location

    # Single contains match.
    contains = [
        (alias, sid)
        for alias, sid in station_maps.default_map.items()
        if query_norm in alias
    ]
    unique_ids = sorted({sid for _alias, sid in contains})
    if len(unique_ids) == 1:
        sid = unique_ids[0]
        return sid, station_label_from_metadata(sid, station_maps) or location
    if len(unique_ids) > 1:
        choices = ", ".join(f"{alias} ({sid})" for alias, sid in contains[:15])
        raise ValueError(
            f"Location '{location}' matched multiple stations in {station_maps.source}: "
            f"{choices}. Use --station-id."
        )

    # Fuzzy matching over aliases.
    close = difflib.get_close_matches(query_norm, list(station_maps.default_map.keys()), n=8, cutoff=0.65)
    close_ids = sorted({station_maps.default_map[name] for name in close})
    if len(close_ids) == 1 and close:
        sid = close_ids[0]
        print(f"Matched location '{location}' to alias '{close[0]}' ({sid}) from {station_maps.source}.")
        return sid, station_label_from_metadata(sid, station_maps) or close[0]

    if close:
        choices = ", ".join(f"{name} ({station_maps.default_map[name]})" for name in close)
        raise ValueError(
            f"Could not uniquely match '{location}'. Close matches from {station_maps.source}: "
            f"{choices}. Use --station-id."
        )

    raise ValueError(
        f"Could not match location '{location}' to a station ID using {station_maps.source}. "
        "Try --station-id, run with --refresh-station-map, or pass --station-map petss_station_map.py."
    )



def load_datum_lookup(path: Path) -> pd.DataFrame:
    """
    Load a station datum lookup table.

    Supported formats:

    1. Output from build_petss_datum_lookup.py, with columns like:
       station_id, mhhw_minus_mllw_ft, coops_station_id, datum_epoch, status

    2. Master coastal-site spreadsheet, with columns like:
       Station ID, Station Name, MHHW, MLLW, MSL, HAT, NWSLI, Obs?, Tide?

    For the master spreadsheet, mhhw_minus_mllw_ft is computed as:

       MHHW - MLLW

    and this script then converts PETSS forecast values using:

       value_MHHW = value_MLLW - (MHHW - MLLW)
    """
    raw = pd.read_csv(path, dtype=str)

    # Preserve original names so we can support display metadata, then create
    # a normalized lower/snake-ish set of column names for matching.
    original_columns = list(raw.columns)
    df = raw.copy()
    df.columns = [
        c.strip()
        .lower()
        .replace(" ", "_")
        .replace("?", "")
        .replace("/", "_")
        .replace("-", "_")
        for c in df.columns
    ]

    # Case 1: build_petss_datum_lookup.py output.
    if {"station_id", "mhhw_minus_mllw_ft"}.issubset(df.columns):
        if "status" in df.columns:
            df = df[df["status"].astype(str).str.lower() == "ok"].copy()

        df["station_id"] = df["station_id"].astype(str).str.strip()
        df["mhhw_minus_mllw_ft"] = pd.to_numeric(df["mhhw_minus_mllw_ft"], errors="coerce")

        # Normalize expected optional metadata columns.
        if "coops_station_id" not in df.columns:
            df["coops_station_id"] = df["station_id"]
        if "coops_station_name" not in df.columns and "station_name" in df.columns:
            df["coops_station_name"] = df["station_name"]
        if "datum_epoch" not in df.columns:
            df["datum_epoch"] = pd.NA

    # Case 2: master spreadsheet.
    elif {"station_id", "mhhw", "mllw"}.issubset(df.columns):
        df["station_id"] = df["station_id"].astype(str).str.strip()
        df["mhhw_ft"] = pd.to_numeric(df["mhhw"], errors="coerce")
        df["mllw_ft"] = pd.to_numeric(df["mllw"], errors="coerce")
        df["mhhw_minus_mllw_ft"] = df["mhhw_ft"] - df["mllw_ft"]

        # Match the metadata names used downstream by get_datum_conversion().
        df["coops_station_id"] = df["station_id"]
        if "station_name" in df.columns:
            df["coops_station_name"] = df["station_name"]
        else:
            df["coops_station_name"] = pd.NA

        # The master spreadsheet may not include an epoch. Keep a column so the
        # cleaned output has a consistent schema.
        if "datum_epoch" not in df.columns:
            df["datum_epoch"] = pd.NA

    else:
        raise ValueError(
            "Datum lookup format not recognized. Expected either columns "
            "station_id/mhhw_minus_mllw_ft or master-sheet columns "
            "Station ID/MHHW/MLLW. Found columns: " + ", ".join(original_columns)
        )

    df = df.dropna(subset=["station_id", "mhhw_minus_mllw_ft"])
    df = df.drop_duplicates(subset=["station_id"], keep="first")

    if df.empty:
        raise ValueError(f"No usable datum rows found in {path}")

    return df.set_index("station_id")


def get_datum_conversion(
    *,
    station_id: str,
    vertical_datum: str,
    datum_lookup_path: Path | None,
) -> DatumConversion:
    """
    Return the vertical datum conversion for this station.

    PETSS CSV values are assumed to be referenced to MLLW. If vertical_datum is
    MHHW, the conversion applied later is:

        value_MHHW = value_MLLW - (MHHW - MLLW)
    """
    requested = vertical_datum.upper()

    if requested == "MLLW":
        return DatumConversion(station_id=station_id, vertical_datum="MLLW", source="no conversion")

    if requested != "MHHW":
        raise ValueError("Only MLLW and MHHW are supported for --vertical-datum.")

    if datum_lookup_path is None:
        raise ValueError(
            "--vertical-datum MHHW requires a datum lookup CSV. "
            "Pass --datum-lookup petss_station_datums.csv or use --vertical-datum MLLW."
        )

    if not datum_lookup_path.exists():
        raise FileNotFoundError(
            f"Datum lookup file not found: {datum_lookup_path}. "
            "Place petss_station_datums.csv in the working folder, pass the full path with "
            "--datum-lookup, or use --vertical-datum MLLW."
        )

    lookup = load_datum_lookup(datum_lookup_path)
    sid = str(station_id).strip()

    if sid not in lookup.index:
        raise ValueError(
            f"No MHHW/MLLW datum lookup row found for station {sid} in {datum_lookup_path}. "
            "Use --vertical-datum MLLW, add the station to the datum lookup, or run "
            "build_petss_datum_lookup.py with --allow-name-match and review the result."
        )

    row = lookup.loc[sid]
    if isinstance(row, pd.DataFrame):
        row = row.iloc[0]

    offset = pd.to_numeric(row["mhhw_minus_mllw_ft"], errors="coerce")
    if pd.isna(offset):
        raise ValueError(f"Datum row for station {sid} does not have a valid mhhw_minus_mllw_ft value.")

    return DatumConversion(
        station_id=sid,
        vertical_datum="MHHW",
        mhhw_minus_mllw_ft=float(offset),
        coops_station_id=str(row.get("coops_station_id", "")) or None,
        coops_station_name=str(row.get("coops_station_name", "")) or None,
        datum_epoch=str(row.get("datum_epoch", "")) or None,
        source=str(datum_lookup_path),
    )


def apply_vertical_datum_conversion(
    df: pd.DataFrame,
    conversion: DatumConversion,
    *,
    columns: tuple[str, ...] = ("TWL", "TWL10p", "TWL90p"),
) -> pd.DataFrame:
    """
    Convert PETSS forecast water-level columns from MLLW to the requested datum.

    For MHHW:
        value_ft_MHHW = value_ft_MLLW - (MHHW_ft - MLLW_ft)

    Tide/observation columns are intentionally not converted here because the
    customer-facing graphic does not plot them and their datum basis should be
    confirmed separately before transforming them.
    """
    out = df.copy()

    out["vertical_datum"] = conversion.vertical_datum
    out["mhhw_minus_mllw_ft"] = conversion.mhhw_minus_mllw_ft
    out["datum_source"] = conversion.source
    out["coops_station_id"] = conversion.coops_station_id
    out["coops_station_name"] = conversion.coops_station_name
    out["datum_epoch"] = conversion.datum_epoch

    if conversion.vertical_datum == "MHHW":
        if conversion.mhhw_minus_mllw_ft is None:
            raise ValueError("MHHW conversion requested, but mhhw_minus_mllw_ft is missing.")

        for col in columns:
            if col in out.columns:
                out[col] = pd.to_numeric(out[col], errors="coerce") - conversion.mhhw_minus_mllw_ft

    return out


def safe_tar_member_name(member: tarfile.TarInfo) -> str:
    """Return normalized member name and reject unsafe absolute/path-traversal names."""
    name = member.name.replace("\\", "/")
    parts = [p for p in name.split("/") if p not in ("", ".")]
    if any(p == ".." for p in parts) or name.startswith("/"):
        raise ValueError(f"Unsafe path in tar archive: {member.name}")
    return "/".join(parts)


def find_station_member(tar_path: Path, station_id: str) -> tarfile.TarInfo:
    """Find a station CSV member inside the PETSS tarball."""
    target = f"{station_id}.csv".lower()

    with tarfile.open(tar_path, "r:gz") as tf:
        matches = []
        for member in tf.getmembers():
            if not member.isfile():
                continue
            name = safe_tar_member_name(member)
            if Path(name).name.lower() == target:
                matches.append(member)

        if len(matches) == 1:
            return matches[0]
        if len(matches) > 1:
            names = [m.name for m in matches]
            raise RuntimeError(f"Found multiple CSVs for station {station_id}: {names}")

    raise FileNotFoundError(f"Station CSV {station_id}.csv was not found in {tar_path}")


def extract_station_csv(tar_path: Path, station_id: str, output_dir: Path, overwrite: bool = False) -> Path:
    """Extract only the requested station CSV from the tarball."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{station_id}.csv"

    if output_path.exists() and output_path.stat().st_size > 0 and not overwrite:
        print(f"Using cached station CSV: {output_path}")
        return output_path

    with tarfile.open(tar_path, "r:gz") as tf:
        member = find_station_member(tar_path, station_id)
        extracted = tf.extractfile(member)
        if extracted is None:
            raise RuntimeError(f"Could not extract {member.name}")
        output_path.write_bytes(extracted.read())

    print(f"Extracted station CSV: {output_path}")
    return output_path


def read_petss_station_csv(
    csv_path: Path,
    cycle: PetssCycle | None = None,
    station_id: str | None = None,
    station_name: str | None = None,
) -> pd.DataFrame:
    """Read a PETSS station CSV and return a cleaned pandas DataFrame."""
    df = pd.read_csv(csv_path, skipinitialspace=True)
    df.columns = [c.strip() for c in df.columns]

    if "TIME" not in df.columns:
        raise ValueError(f"Expected a TIME column in {csv_path}; columns are: {list(df.columns)}")

    df["valid_time"] = pd.to_datetime(df["TIME"].astype(str), format="%Y%m%d%H%M", utc=True, errors="coerce")

    numeric_cols = [c for c in df.columns if c not in {"TIME", "valid_time"}]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].where(~df[col].isin(MISSING_VALUES), pd.NA)

    if cycle is not None:
        df["run_time"] = cycle.run_time_utc
        df["forecast_hour"] = (df["valid_time"] - cycle.run_time_utc) / pd.Timedelta(hours=1)
    else:
        df["run_time"] = pd.NaT
        df["forecast_hour"] = pd.NA

    if station_id is None:
        station_id = csv_path.stem

    df["station_id"] = str(station_id)
    df["station_name"] = station_name

    first_cols = ["station_id", "station_name", "run_time", "valid_time", "forecast_hour"]
    other_cols = [c for c in df.columns if c not in first_cols]
    return df[first_cols + other_cols]


def download_and_read_station(
    *,
    date: str | None,
    cycle_hour: str | None,
    station_id: str | None,
    location: str | None,
    region: str,
    outdir: Path,
    station_map_path: Path | None,
    refresh_map: bool,
    station_map_builder: Path,
    datum_lookup_path: Path | None,
    vertical_datum: str,
    overwrite: bool,
) -> tuple[pd.DataFrame, PetssCycle, Path]:
    """Complete workflow: resolve cycle, resolve station, download tarball, extract CSV, read DataFrame."""
    if date and cycle_hour:
        cycle = PetssCycle(date=date, cycle=f"{int(cycle_hour):02d}")
    elif date or cycle_hour:
        raise ValueError("Use both --date and --cycle together, or omit both to use latest available.")
    else:
        cycle = find_latest_cycle()
        print(f"Latest available PETSS CSV cycle appears to be {cycle.date} t{cycle.cycle}z")

    # If requested, rebuild petss_station_map.py using the same date/cycle when provided,
    # otherwise use latest available storm tide text file.
    if refresh_map:
        target_station_map = station_map_path or Path("petss_station_map.py")
        refresh_station_map(
            builder_script=station_map_builder,
            output_py=target_station_map,
            region=region,
            date=date,
            cycle=cycle_hour,
            latest=not (date and cycle_hour),
            overwrite=overwrite,
        )
        station_map_path = target_station_map

    station_maps = load_station_maps(station_map_path)
    print(f"Station-map source: {station_maps.source}")

    resolved_station_id, resolved_station_name = resolve_station_id(
        station_id=station_id,
        location=location,
        station_maps=station_maps,
    )
    print(f"Using station: {resolved_station_id}" + (f" ({resolved_station_name})" if resolved_station_name else ""))

    tar_path = outdir / "raw" / cycle.date / f"t{cycle.cycle}z" / cycle.tar_name
    download_file(cycle.tar_url, tar_path, overwrite=overwrite)

    station_csv_dir = outdir / "stations" / cycle.date / f"t{cycle.cycle}z"
    csv_path = extract_station_csv(tar_path, resolved_station_id, station_csv_dir, overwrite=overwrite)

    df = read_petss_station_csv(
        csv_path,
        cycle=cycle,
        station_id=resolved_station_id,
        station_name=resolved_station_name,
    )

    conversion = get_datum_conversion(
        station_id=resolved_station_id,
        vertical_datum=vertical_datum,
        datum_lookup_path=datum_lookup_path,
    )
    df = apply_vertical_datum_conversion(df, conversion)

    if conversion.vertical_datum == "MHHW":
        print(
            f"Converted TWL/TWL10p/TWL90p from MLLW to MHHW using "
            f"MHHW-MLLW = {conversion.mhhw_minus_mllw_ft:.2f} ft"
            + (f" from {conversion.source}" if conversion.source else "")
        )
    else:
        print("Using PETSS water levels as MLLW-referenced values.")

    return df, cycle, csv_path



def clean_station_display_name(station_label: str | None, station_id: str | None = None) -> str:
    """
    Remove station IDs and tidy PETSS station labels for customer-facing graphics.
    """
    if not station_label:
        return station_id or "Selected location"

    name = str(station_label)

    # Remove parenthetical station IDs, e.g. "Nome (9468756)".
    name = re.sub(r"\s*\([A-Za-z0-9]{4,}\)\s*$", "", name)

    # Remove explicit station ID if appended.
    if station_id:
        name = name.replace(str(station_id), "")

    # PETSS labels often use all caps or hyphens.
    name = name.replace("-", " ")
    name = re.sub(r"\s+", " ", name).strip(" ,")

    # Remove trailing AK for cleaner title.
    name = re.sub(r",?\s*AK$", "", name, flags=re.IGNORECASE).strip(" ,")

    # Title case, but keep common words readable.
    return name.title()


def safe_filename_part(value: str) -> str:
    """
    Create a filesystem-safe filename component from a community/station name.
    """
    value = clean_station_display_name(value)
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value or "selected_location"


def local_time_label(tz_name: str) -> str:
    """
    Return a short timezone label for axis/title text.
    """
    now_local = pd.Timestamp.now(tz=ZoneInfo(tz_name))
    return now_local.strftime("%Z") or tz_name


def format_local_time(dt, *, include_date: bool = True) -> str:
    """
    Cross-platform local time formatter.

    Avoids strftime codes like %-I, which work on Linux/macOS but fail on Windows.
    """
    ts = pd.Timestamp(dt)

    if include_date:
        # Example: Tue Jun 23, 8 PM
        return f"{ts.strftime('%a %b')} {ts.day}, {ts.strftime('%I').lstrip('0') or '0'} {ts.strftime('%p')}"

    # Example: Tue 8 PM
    return f"{ts.strftime('%a')} {ts.strftime('%I').lstrip('0') or '0'} {ts.strftime('%p')}"



def plot_twl(
    df: pd.DataFrame,
    output_path: Path,
    station_label: str | None = None,
    title: str | None = None,
    scenario_low_label: str = "Lower possible outcome",
    scenario_high_label: str = "Higher possible outcome",
    main_label: str = "Expected water level",
    show_scenario_lines: bool = True,
    timezone: str = "America/Anchorage",
    show_peak_callout: bool = True,
) -> Path:
    """
    Customer-facing PETSS total water level forecast graphic.

    Layout choices are tuned to keep all annotations inside the plotted figure:
      - local Alaska time on the x-axis
      - peak callout anchored inside the axes
      - wrapped disclaimer inside the axes
      - tighter figure bounds with no large empty whitespace
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if "TWL" not in df.columns:
        raise ValueError(f"No TWL column found. Available columns: {list(df.columns)}")

    tz = ZoneInfo(timezone)
    tz_label = local_time_label(timezone)

    plot_df = df.sort_values("valid_time").copy()
    plot_df["valid_time"] = pd.to_datetime(plot_df["valid_time"], utc=True, errors="coerce")

    if "run_time" in plot_df.columns and plot_df["run_time"].notna().any():
        run_time_utc = pd.to_datetime(plot_df["run_time"].dropna().iloc[0], utc=True)
        plot_df = plot_df[plot_df["valid_time"] >= run_time_utc].copy()
    else:
        run_time_utc = pd.NaT

    plot_df["plot_time"] = plot_df["valid_time"].dt.tz_convert(tz)
    twl_df = plot_df.dropna(subset=["plot_time", "TWL"]).copy()

    # Slightly taller figure to comfortably fit title and note.
    fig, ax = plt.subplots(figsize=(11, 7.2))

    peak_time = None
    peak_value = None

    pct_available = {"TWL10p", "TWL90p"}.issubset(plot_df.columns)
    if pct_available:
        pct_df = plot_df.dropna(subset=["plot_time", "TWL10p", "TWL90p"]).copy()
        if not pct_df.empty:
            p10 = pd.to_numeric(pct_df["TWL10p"], errors="coerce")
            p90 = pd.to_numeric(pct_df["TWL90p"], errors="coerce")
            lower = pd.concat([p10, p90], axis=1).min(axis=1)
            upper = pd.concat([p10, p90], axis=1).max(axis=1)

            pct_df = pct_df.assign(_lower=lower, _upper=upper)

            ax.fill_between(
                pct_df["plot_time"],
                pct_df["_lower"],
                pct_df["_upper"],
                alpha=0.22,
                label="Possible range",
                zorder=1,
            )

            if show_scenario_lines:
                ax.plot(
                    pct_df["plot_time"],
                    pct_df["_lower"],
                    linewidth=1.5,
                    linestyle="--",
                    label=scenario_low_label,
                    zorder=2,
                )
                ax.plot(
                    pct_df["plot_time"],
                    pct_df["_upper"],
                    linewidth=1.8,
                    linestyle="--",
                    label=scenario_high_label,
                    zorder=2,
                )

            peak_idx = pct_df["_upper"].idxmax()
            peak_time = pct_df.loc[peak_idx, "plot_time"]
            peak_value = float(pct_df.loc[peak_idx, "_upper"])

    if not twl_df.empty:
        ax.plot(
            twl_df["plot_time"],
            pd.to_numeric(twl_df["TWL"], errors="coerce"),
            linewidth=3,
            marker="o",
            markersize=2.5,
            label=main_label,
            zorder=3,
        )

        if peak_time is None:
            peak_idx = pd.to_numeric(twl_df["TWL"], errors="coerce").idxmax()
            peak_time = twl_df.loc[peak_idx, "plot_time"]
            peak_value = float(twl_df.loc[peak_idx, "TWL"])
    else:
        print("Warning: TWL column exists but contains no valid forecast values to plot.")

    station_id = str(plot_df["station_id"].iloc[0]) if "station_id" in plot_df.columns and len(plot_df) else None
    display_name = clean_station_display_name(station_label, station_id=station_id)

    vertical_datum = "MLLW"
    if "vertical_datum" in plot_df.columns and plot_df["vertical_datum"].notna().any():
        vertical_datum = str(plot_df["vertical_datum"].dropna().iloc[0]).upper()

    if title is None:
        if pd.notna(run_time_utc):
            run_time_local = pd.Timestamp(run_time_utc).tz_convert(tz)
            run_str = format_local_time(run_time_local, include_date=True)
            title = f"Water Level Forecast for {display_name} Forecast issued: {run_str} {tz_label}"
        else:
            title = f"Water Level Forecast for {display_name}"

    ax.set_title(title, fontsize=19, fontweight="bold", pad=14)
    ax.set_xlabel(f"Date and time ({tz_label})", fontsize=12)

    if vertical_datum == "MHHW":
        ax.set_ylabel("Water height above normal high tide (feet)", fontsize=12)
    else:
        ax.set_ylabel(f"Water level above {vertical_datum} (feet)", fontsize=12)

    ax.grid(True, alpha=0.35)
    ax.legend(loc="upper left", frameon=True, fontsize=10)
    ax.tick_params(axis="both", labelsize=10)
    ax.margins(x=0.02)

    if show_peak_callout and peak_time is not None and peak_value is not None:
        peak_label_time = format_local_time(peak_time, include_date=False)

        # Shorter, wrapped customer-facing callout text
        callout = (
            f"Peak higher\n"
            f"scenario\n"
            f"{peak_value:.1f} ft above\n"
            f"normal high tide\n"
            f"{peak_label_time} {tz_label}"
        )

        ax.scatter([peak_time], [peak_value], s=55, zorder=5)

        # --- Smarter placement logic ---
        # Use the peak location relative to the data extent to decide which direction
        # to offset the label so it stays inside the axes and away from the title.
        x_min = plot_df["plot_time"].min()
        x_max = plot_df["plot_time"].max()
        y_min, y_max = ax.get_ylim()

        x_frac = (peak_time - x_min) / (x_max - x_min) if x_max != x_min else 0.5
        y_frac = (peak_value - y_min) / (y_max - y_min) if y_max != y_min else 0.5

        # Default quadrant-based offset:
        #   top-left     -> right/down
        #   top-right    -> left/down
        #   bottom-left  -> right/up
        #   bottom-right -> left/up
        if x_frac < 0.5:
            dx = 55
            ha = "left"
        else:
            dx = -55
            ha = "right"

        if y_frac > 0.7:
            dy = -18
            va = "top"
        else:
            dy = 18
            va = "bottom"

        # Extra protection so the callout does not land in the legend area
        # (upper-left) or get too close to the title.
        if x_frac < 0.35 and y_frac > 0.60:
            dx = 70
            dy = -22
            ha = "left"
            va = "top"

        ax.annotate(
            callout,
            xy=(peak_time, peak_value),
            xycoords="data",
            xytext=(dx, dy),
            textcoords="offset points",
            fontsize=9,
            fontweight="bold",
            ha=ha,
            va=va,
            arrowprops={
                "arrowstyle": "->",
                "lw": 1.2,
                "shrinkA": 4,
                "shrinkB": 4,
            },
            bbox={
                "boxstyle": "round,pad=0.35",
                "facecolor": "white",
                "alpha": 0.94,
                "edgecolor": "0.35",
            },
            annotation_clip=True,
            zorder=6,
        )
    note = (
        "Shaded area shows a reasonable range of outcomes. "
        "Actual water levels may fall outside this range."
    )
    if vertical_datum == "MHHW":
        note += " Reference: normal high tide (MHHW)."

    note = textwrap.fill(note, width=70)
    ax.text(
        0.01,
        0.02,
        note,
        transform=ax.transAxes,
        fontsize=9,
        va="bottom",
        ha="left",
        bbox={"boxstyle": "round,pad=0.35", "facecolor": "white", "alpha": 0.82, "edgecolor": "0.8"},
        zorder=6,
    )

    # Manually set figure bounds so title is not clipped and bottom note has room.
    fig.subplots_adjust(left=0.11, right=0.98, top=0.88, bottom=0.18)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote plot: {output_path}")
    return output_path


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download PETSS CSV tarball, extract a station CSV, and plot TWL.")

    parser.add_argument("--date", help="PETSS date in YYYYMMDD. Omit with --cycle to auto-detect latest available.")
    parser.add_argument("--cycle", choices=RUN_CYCLES, help="Cycle hour: 00, 06, 12, or 18. Omit with --date to auto-detect latest available.")

    station_group = parser.add_mutually_exclusive_group(required=True)
    station_group.add_argument("--station-id", help="Station ID, e.g. 9468756 for Nome.")
    station_group.add_argument("--location", help="Station name or partial name, e.g. Nome.")

    parser.add_argument("--region", default="nwak", help="PETSS text-region code used to build station-name map. Default: nwak.")
    parser.add_argument(
        "--station-map",
        type=Path,
        help=(
            "Optional generated station map. Preferred: petss_station_map.py from build_petss_station_map.py. "
            "Also supports .json or simple .csv."
        ),
    )
    parser.add_argument(
        "--refresh-station-map",
        action="store_true",
        help="Run build_petss_station_map.py before resolving --location.",
    )
    parser.add_argument(
        "--station-map-builder",
        type=Path,
        default=Path("build_petss_station_map.py"),
        help="Path to build_petss_station_map.py. Used only with --refresh-station-map.",
    )
    parser.add_argument(
        "--datum-lookup",
        type=Path,
        default=Path("petss_station_datums.csv"),
        help=(
            "Datum CSV used for MHHW conversion. Defaults to petss_station_datums.csv "
            "in the working folder. Supports either sites_and_datums.csv master sheet "
            "with Station ID/MHHW/MLLW columns, or output from build_petss_datum_lookup.py."
        ),
    )
    parser.add_argument(
        "--vertical-datum",
        choices=("MLLW", "MHHW"),
        default="MHHW",
        help=(
            "Vertical datum for plotted forecast water levels. PETSS is assumed "
            "to start as MLLW. Default: MHHW."
        ),
    )
    parser.add_argument("--outdir", type=Path, default=Path("petss_data"), help="Output/cache directory.")
    parser.add_argument("--overwrite", action="store_true", help="Re-download/re-extract existing files.")
    parser.add_argument("--no-plot", action="store_true", help="Only download/extract/read/write cleaned CSV; do not plot.")
    parser.add_argument("--scenario-low-label", default="Lower possible outcome", help="Plain-language label for the lower scenario line.")
    parser.add_argument("--scenario-high-label", default="Higher possible outcome", help="Plain-language label for the higher scenario line.")
    parser.add_argument("--main-label", default="Expected water level", help="Plain-language label for the TWL forecast line.")
    parser.add_argument("--hide-scenario-lines", action="store_true", help="Show only the shaded scenario range and main TWL line.")
    parser.add_argument(
        "--timezone",
        default="America/Anchorage",
        help="IANA timezone used for the x-axis and forecast-issued time. Default: America/Anchorage.",
    )
    parser.add_argument(
        "--no-peak-callout",
        action="store_true",
        help="Disable the peak higher-scenario callout box.",
    )

    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)

    try:
        df, cycle, csv_path = download_and_read_station(
            date=args.date,
            cycle_hour=args.cycle,
            station_id=args.station_id,
            location=args.location,
            region=args.region,
            outdir=args.outdir,
            station_map_path=args.station_map,
            refresh_map=args.refresh_station_map,
            station_map_builder=args.station_map_builder,
            datum_lookup_path=args.datum_lookup,
            vertical_datum=args.vertical_datum,
            overwrite=args.overwrite,
        )

        station_id = str(df["station_id"].iloc[0])
        products_dir = args.outdir / "products" / cycle.date / f"t{cycle.cycle}z"
        products_dir.mkdir(parents=True, exist_ok=True)

        datum_label = str(df["vertical_datum"].iloc[0]).lower() if "vertical_datum" in df.columns else "mllw"
        cleaned_path = products_dir / f"petss_{cycle.date}_t{cycle.cycle}z_{station_id}_{datum_label}_clean.csv"
        df.to_csv(cleaned_path, index=False)
        print(f"Wrote cleaned CSV: {cleaned_path}")

        if not args.no_plot:
            station_name = df["station_name"].iloc[0]
            station_label = clean_station_display_name(station_name, station_id=station_id) if isinstance(station_name, str) and station_name else station_id
            location_part = safe_filename_part(station_label)
            plot_path = products_dir / f"petss_{cycle.date}_t{cycle.cycle}z_{location_part}_{datum_label}_twl.png"
            plot_twl(
                df,
                plot_path,
                station_label=station_label,
                scenario_low_label=args.scenario_low_label,
                scenario_high_label=args.scenario_high_label,
                main_label=args.main_label,
                show_scenario_lines=not args.hide_scenario_lines,
                timezone=args.timezone,
                show_peak_callout=not args.no_peak_callout,
            )

        print("\nDataFrame preview:")
        with pd.option_context("display.max_columns", 20, "display.width", 160):
            print(df.head())

        print(f"\nOriginal station CSV: {csv_path}")
        return 0

    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
